### ISSUE TITLE
AccountDoesNotExistError(f"Account {address} does not exist")

### ISSUE THREAD

**Issue by Full4me** [0xbigz/driftpy-arb#1]
I work with paper wallet and Your code. I import file with wallet and when I try to `.get_user_account()` I got error:

`  raise AccountDoesNotExistError(f"Account {address} does not exist")
anchorpy.error.AccountDoesNotExistError: Account (...) does not exist`

Any idea why that happen?

**Comment by Kalindro** [comment]
Hi, me and Full are dabbling with defis APIs to try our cefi solution in this environment, could you @0xbigz advise you what point are we messing for the making the account work?

**Comment by 0xbigz** [comment]
hi take a look at initialize_user_account_and_deposit_collateral instruction if the account DNE

```
?drift_acct.initialize_user_account_and_deposit_collateral

Signature:
drift_acct.initialize_user_account_and_deposit_collateral(
    amount: int,
    collateral_account_public_key: solana.publickey.PublicKey,
    state: Optional[driftpy.types.StateAccount] = None,
) -> tuple
```

amount is in 1e6 (QUOTE_PRECISION) so 1e6 = 1 USDC
also the solana rent exempt amount is ~.015 SOL
https://docs.drift.trade/faq#lf-whats-the-cost-to-open-a-drift-account

**Comment by Kalindro** [comment]
Thanks, @0xbigz, we've actually tried it before posting here, and we run into:
```
solana.rpc.core.RPCException: {'code': -32002, 'message': 'Transaction simulation failed: Error processing Instruction 1: custom program error: 0xbbf', 'data': {'accounts': None, 'err': {'InstructionError': [1, {'Custom': 3007}]}, 'logs': ['Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN invoke [1]', 'Program log: Instruction: InitializeUser', 'Program 11111111111111111111111111111111 invoke [2]', 'Program 11111111111111111111111111111111 success', 'Program 11111111111111111111111111111111 invoke [2]', 'Program 11111111111111111111111111111111 success', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN consumed 16820 of 200000 compute units', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN success', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN invoke [1]', 'Program log: Instruction: DepositCollateral', 'Program log: Custom program error: 0xbbf', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN consumed 6537 of 200000 compute units', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN failed: custom program error: 0xbbf']}}
```

**Comment by Kalindro** [comment]
Thanks, @0xbigz, we've actually tried it before posting here, and we run into:
```
solana.rpc.core.RPCException: {'code': -32002, 'message': 'Transaction simulation failed: Error processing Instruction 1: custom program error: 0xbbf', 'data': {'accounts': None, 'err': {'InstructionError': [1, {'Custom': 3007}]}, 'logs': ['Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN invoke [1]', 'Program log: Instruction: InitializeUser', 'Program 11111111111111111111111111111111 invoke [2]', 'Program 11111111111111111111111111111111 success', 'Program 11111111111111111111111111111111 invoke [2]', 'Program 11111111111111111111111111111111 success', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN consumed 16820 of 200000 compute units', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN success', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN invoke [1]', 'Program log: Instruction: DepositCollateral', 'Program log: Custom program error: 0xbbf', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN consumed 6537 of 200000 compute units', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN failed: custom program error: 0xbbf']}}
```

```
    drift_acct = await ClearingHouse.create_from_env("mainnet")
    await drift_acct.initialize_user_account_and_deposit_collateral(amount=3000000, collateral_account_public_key="[...]")
```

It may be us being silly, but if we get this sorted it should be downhill from here

**Comment by 0xbigz** [comment]
hey did this get sorted?

**Comment by Full4me** [comment]
@0xbigz No. I didn't.  I just changed place for drift library
`https://github.com/drift-labs/driftpy/issues/7` , because it seemed like a more suitable place for future users with same problem.

**Comment by Kalindro** [comment]
@0xbigz Can you help us on this? We are still facing this issue, is it some basic thing we are missing? We are failing on the initialization itself.

```
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

os.environ["ANCHOR_WALLET"] = "Drift.json"

async def accinit():
    drift_acct = await ClearingHouse.create_from_env("mainnet")
    await drift_acct.initialize_user_account_and_deposit_collateral(amount=3000000, collateral_account_public_key=drift_acct.program.provider.wallet.public_key)
asyncio.run(accinit())

```

```
Traceback (most recent call last):
  File "H:\Drift.py", line 20, in <module>
    asyncio.run(accinit())
  File "C:\Program Files\Python3910\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python3910\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "H:\Drift.py", line 16, in accinit
    await drift_acct.initialize_user_account_and_deposit_collateral(amount=3000000, collateral_account_public_key=drift_acct.program.provider.wallet.public_key)
  File "H:\.venvs\Crypto-Venv3910\lib\site-packages\driftpy\clearing_house.py", line 286, in initialize_user_account_and_deposit_collateral
    tx_sig = await self.program.provider.send(tx, [user_positions_account])
  File "H:\Google Drive Sync\Rzeczy\Projekty_python\.venvs\Crypto-Venv3910\lib\site-packages\anchorpy\provider.py", line 131, in send
    resp = await self.connection.send_transaction(tx, *all_signers, opts=opts)
  File "H:\.venvs\Crypto-Venv3910\lib\site-packages\solana\rpc\async_api.py", line 1179, in send_transaction
    txn_resp = await self.send_raw_transaction(txn.serialize(), opts=opts)
  File "H:\.venvs\Crypto-Venv3910\lib\site-packages\solana\rpc\async_api.py", line 1137, in send_raw_transaction
    return await self.__post_send_with_confirm(*post_send_args)
  File "H:\.venvs\Crypto-Venv3910\lib\site-packages\solana\rpc\async_api.py", line 1236, in __post_send_with_confirm
    resp = self._post_send(resp)
  File "H:\.venvs\Crypto-Venv3910\lib\site-packages\solana\rpc\core.py", line 418, in _post_send
    raise RPCException(error)
solana.rpc.core.RPCException: {'code': -32002, 'message': 'Transaction simulation failed: Error processing Instruction 1: custom program error: 0xbbf', 'data': {'accounts': None, 'err': {'InstructionError': [1, {'Custom': 3007}]}, 'logs': ['Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN invoke [1]', 'Program log: Instruction: InitializeUser', 'Program 11111111111111111111111111111111 invoke [2]', 'Program 11111111111111111111111111111111 success', 'Program 11111111111111111111111111111111 invoke [2]', 'Program 11111111111111111111111111111111 success', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN consumed 16854 of 200000 compute units', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN success', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN invoke [1]', 'Program log: Instruction: DepositCollateral', 'Program log: Custom program error: 0xbbf', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN consumed 6572 of 200000 compute units', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN failed: custom program error: 0xbbf']}}
```

**Comment by Full4me** [comment]
Answer for the problem:
https://github.com/drift-labs/driftpy/issues/7#issuecomment-1048292644
